DOCS = [
    {
        "id": "doc1",
        "title": "Lakehouse Overview",
        "text": """A lakehouse in Microsoft Fabric combines the scalability of a data lake with the querying capabilities of a data warehouse. You store structured and unstructured data in a single location, manage it with Delta Lake format, and analyze it with both Apache Spark and SQL, all without moving data between systems. A lakehouse organizes data into two top-level folders: Tables, which holds managed Delta tables, and Files, which holds unstructured or non-Delta data such as CSVs, images, or Parquet files placed there directly. Only Delta tables show up in the SQL analytics endpoint, so if a table isn't visible there, it usually means the data hasn't been converted to Delta format yet. When you place a file into the Tables folder, Fabric automatically validates it against supported formats and registers it so it becomes queryable through SQL. As of September 2025, Fabric no longer auto-creates a default semantic model when you create a lakehouse; you now create one manually by opening the SQL analytics endpoint view and selecting New semantic model, then choosing which tables to include. With shortcuts in OneLake, a lakehouse can also reference governed data from other workspaces or even other organizations without physically duplicating it, which is useful for cross-team or cross-tenant reporting scenarios."""
    },
    {
        "id": "doc2",
        "title": "Direct Lake Mode",
        "text": """Direct Lake is a Power BI semantic model storage mode available only in Microsoft Fabric. It is designed for large volumes of data that need to be loaded into memory quickly directly from Delta tables in OneLake, without the traditional import step. Once loaded, the semantic model supports high-performance interactive analysis, similar in speed to Import mode but without needing a full data copy. This makes Direct Lake especially useful when replicating an entire dataset into an Import-mode table would be impractical, for example with very large fact tables. Both Direct Lake and Import queries run through the VertiPaq in-memory engine, while DirectQuery instead sends queries back to the source system every time, which tends to be slower. The key architectural difference is in how refresh works: an Import refresh copies the entire dataset again, which can take a long time and consume significant compute, while a Direct Lake refresh only updates metadata (a process called framing) and typically completes in a few seconds, because it simply points to the latest Delta files in OneLake rather than recopying them. Direct Lake requires an F64 or higher capacity to unlock the full feature set alongside Power BI Premium-equivalent capabilities."""
    },
    {
        "id": "doc3",
        "title": "Dataflow Gen2",
        "text": """Dataflow Gen2 is the low-code, no-code data ingestion and transformation tool inside Fabric Data Factory, built on the same Power Query engine used in Excel and Power BI. You connect to a data source, apply transformations through a visual step-by-step interface, and the tool generates M code behind the scenes. Unlike the earlier Power BI Dataflow (now called Gen1), Dataflow Gen2 writes its output directly into Fabric items such as Lakehouses, Warehouses, or Azure SQL Databases, and integrates with scheduled Pipelines, making it a genuine ETL tool rather than just a data-prep helper for a single report. To improve performance, Dataflow Gen2 can stage data in an internal, dataflow-only Lakehouse before writing it to the final destination; staging is enabled by default when loading into a Warehouse, but disabled by default when loading directly into a Lakehouse since the extra hop isn't needed there. Dataflow Gen2 also integrates with Copilot, letting you describe a transformation in natural language (for example, 'remove rows where revenue is null') instead of clicking through the UI manually. Running a Dataflow Gen2 requires a Fabric capacity, a trial capacity, or a Power BI Premium capacity; it will not run on a workspace with no capacity assigned at all."""
    },
    {
        "id": "doc4",
        "title": "Fabric Capacity and Throttling",
        "text": """Every Microsoft Fabric capacity is measured in Capacity Units (CUs), and all workloads in a workspace, such as Spark jobs, dataflow refreshes, and interactive Power BI queries, draw from the same shared CU pool. Capacity SKUs scale in powers of two, from F2 up to F2048; F2 and F4 are mainly intended for individual developers or proof-of-concept work, while F64 is the threshold at which organizations unlock full Direct Lake capability and Power BI Premium-equivalent features, including free viewer access to reports for users without individual Pro licenses. When usage exceeds what a capacity provides, Fabric does not simply reject the request; it applies a smoothing algorithm that spreads short bursts of usage across a rolling 24-hour window, so a brief spike usually doesn't cause any visible slowdown. If sustained usage still exceeds the smoothed allowance, Fabric throttles in stages: first it delays background operations like refreshes and pipeline runs, then it starts rejecting or delaying interactive operations such as report queries, and only in extreme sustained overage does it freeze operations entirely. The Fabric Capacity Metrics app, installed from the Power BI Apps section, is the standard tool for monitoring CU consumption per workspace and catching throttling risk before it affects users; the general guidance is to scale up when smoothed utilization consistently sits above roughly 80 percent, and to consider scaling down if it stays below about 30 percent for an extended period."""
    },
    {
        "id": "doc5",
        "title": "Fabric REST APIs for Automation",
        "text": """Microsoft Fabric exposes REST APIs that let you manage items like dataflows, lakehouses, and pipelines programmatically instead of through the portal UI, which is useful for CI/CD pipelines, scheduled automation, and monitoring. For Dataflow Gen2 specifically, the API supports full CRUD operations: creating a new dataflow with its sources and transformations defined, reading configuration and execution history, updating transformation logic or destinations, and deleting dataflows that are no longer needed. Common automation scenarios include deploying the same dataflow definition across development, test, and production workspaces as part of a CI/CD process, and setting up monitoring that triggers an alert when a scheduled refresh fails. Authentication against the Fabric REST APIs follows the same Microsoft Entra (Azure AD) app registration pattern used across the Microsoft 365 and Azure ecosystem: you register an application, generate a client ID and client secret (or use a certificate), grant the app the relevant API permissions, and then request an OAuth2 access token before calling the API. Because Fabric items live inside a workspace, most API calls require both the item ID and the workspace ID, and the calling identity (whether a user or a service principal) must have at least the appropriate workspace role, such as Contributor, to perform the requested action."""
    },
]
